FROM postgres:15
LABEL Author="Brian H Wilson"

# I really want ip and ps and ping commands here. I mean, come on! I need them.
RUN apt-get update && apt-get install -y procps iproute2 iputils-ping

# Add files to support Esri ArcGIS geometry

COPY PostgreSQL/15/Linux64/st_geometry.so /usr/lib/postgresql/15/lib
# I wonder what this file is for?
COPY PostgreSQL/15/Linux64/PGSQLEngine.so /usr/lib/postgresql/15/lib

VOLUME /var/lib/postgresql/data
